### ISSUE TITLE
zoom knop naamgeving

### ISSUE THREAD

**Issue by stvno** [Amsterdam/stijl#5]
De styling van de zoom knoppen gebruikt een eigen naamgeving (embed-zoom__in etc) echter de gebruikte kaart bibilotheek (leaflet) laat het niet toe om andere klassenamen aan de knoppen toe te kennen.
Bij de data.amsterdam.nl kaartviewer is het opgelost door gewoon de leaflet klasse-namen te gebruiken: https://data.amsterdam.nl/#?mpb=topografie&mpz=11&mpfs=T&mpv=52.3731081:4.8932945&pgn=home&uvm=T 

Ik zou zeggen dat dat hier ook handig is, of in ieder geval ook de leaflet naamgeving te ondersteunen

**Comment by boris-arkenaar** [comment]
Ja dat lijkt mij ook de handigste aanpak. We gaan de leaflet class namen ook ondersteunen vanuit onze stijling repo.

**Comment by vjawala** [comment]
Geupdate, @stvno kunnen jullie er nu mee uit de voeten?

**Comment by stvno** [comment]
Ik moet ook de leaflet css inladen (anders gaan de kaartjes de mist in), dus je zal wat classes moeten overrulen. Hij ziet er nu zo uit:

![image](https://user-images.githubusercontent.com/394323/39759729-b7b6f69e-52d3-11e8-833e-9a20026a6c2f.png)

**Comment by vjawala** [comment]
ah, ik heb het geupdate (wat !important dingen toegevoegd, nu zou het er beter uit moeten zien)
