### ISSUE TITLE
zoek button icoon is hardcoded

### ISSUE THREAD

**Issue by stvno** [Amsterdam/stijl#6]
In het bijgeleverde voorbeeld is het zoek icoontje een hardcoded SVG met eigen klassenaam en styling. Dit betekent dat ik niet makkelijk dit specifieke icoontje kan gebruiken, het lijkt mij logischer om het icoontje via CSS te zetten

eg:
```
.embed-search__button {
     background: url('images/svg/search-icon-white.svg');        
}
```

**Comment by vjawala** [comment]
geupdate, @stvno kan je het checken?

**Comment by stvno** [comment]
top werkt als een zonnetje
